/**
 * Midnight Provider Setup for Browser DApp
 * 
 * Assembles the full MidnightProviders object from the DApp Connector (Lace wallet).
 * Based on the official bboard-ui example pattern:
 *   - publicDataProvider from indexer
 *   - walletProvider + midnightProvider from DApp connector API
 *   - zkConfigProvider from FetchZkConfigProvider (serves ZK artifacts over HTTP)
 *   - proofProvider from HTTP proof server
 *   - privateStateProvider from level-db (browser IndexedDB)
 */

import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { FetchZkConfigProvider } from '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { MidnightProviders } from '@midnight-ntwrk/midnight-js-types';
import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import { Transaction } from '@midnight-ntwrk/ledger-v8';

// Contract bindings generated by `compact compile`
import { Contract, ledger } from '@/contracts/zk_creator';
import type { Witnesses, Ledger } from '@/contracts/zk_creator';

// The deployed contract address on Preprod
export const PREPROD_CONTRACT_ADDRESS = 'd9feb2468cb2325da4bb6709d5b278631d3f113fda43265a032d21db4cb066db';

// Circuit key type for our contract
type ZkCreatorCircuitKeys = 'unlock';

// Private state type (our contract has no private state beyond the circuit witness)
type ZkCreatorPrivateState = Record<string, never>;

// Helper: convert Uint8Array to hex string
function toHex(bytes: Uint8Array): string {
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
}

// Helper: convert hex string to Uint8Array
function fromHex(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

/**
 * Build the compiled contract object needed by midnight-js-contracts.
 * The FetchZkConfigProvider serves the ZK artifacts, and the Contract class
 * provides the circuit logic.
 */
function buildCompiledContract() {
  const contract = new Contract({} as Witnesses<ZkCreatorPrivateState>);
  return {
    contract,
    // The compiled contract includes the runtime contract + reference to circuit IDs
    impureCircuits: contract.impureCircuits,
    initialState: contract.initialState.bind(contract),
  };
}

/**
 * Initialize all Midnight providers from the DApp Connector (Lace wallet).
 * 
 * This follows the exact pattern from the official Midnight bboard-ui example.
 */
export async function initializeProviders(
  connectedAPI: ConnectedAPI
): Promise<MidnightProviders> {
  // Set network to preprod
  setNetworkId('preprod');

  // Get wallet configuration (indexer URIs, prover server, etc.)
  const config = await connectedAPI.getConfiguration();
  console.log('[Midnight] Wallet configuration:', {
    indexerUri: config.indexerUri,
    indexerWsUri: config.indexerWsUri,
    proverServerUri: config.proverServerUri,
    networkId: config.networkId,
  });

  // Get shielded addresses for wallet provider
  const shieldedAddresses = await connectedAPI.getShieldedAddresses();

  // ZK Config Provider — serves prover keys, verifier keys, and ZKIR from the app origin
  // These files must be available at: /keys/unlock.prover, /keys/unlock.verifier, /zkir/unlock.bzkir
  const zkConfigProvider = new FetchZkConfigProvider<ZkCreatorCircuitKeys>(
    window.location.origin,
    fetch.bind(window)
  );

  // Private state provider — stores contract private state in browser IndexedDB
  const privateStateProvider = levelPrivateStateProvider({
    privateStoragePasswordProvider: () => 'NightGate-Preprod-2026!',
    accountId: shieldedAddresses.shieldedCoinPublicKey,
  });

  // Public data provider — queries on-chain state via the indexer GraphQL API
  const publicDataProvider = indexerPublicDataProvider(
    config.indexerUri,
    config.indexerWsUri
  );

  // Proof provider — sends proof requests to the prover server from wallet config
  const proofProvider = httpClientProofProvider(
    config.proverServerUri!,
    zkConfigProvider
  );

  // Wallet provider — exposes wallet keys and transaction balancing via DApp connector
  const walletProvider = {
    getCoinPublicKey(): string {
      return shieldedAddresses.shieldedCoinPublicKey;
    },
    getEncryptionPublicKey(): string {
      return shieldedAddresses.shieldedEncryptionPublicKey;
    },
    balanceTx: async (tx: any): Promise<any> => {
      const serializedTx = toHex(tx.serialize());
      const received = await connectedAPI.balanceUnsealedTransaction(serializedTx);
      return Transaction.deserialize(
        'signature' as any,
        'proof' as any,
        'binding' as any,
        fromHex(received.tx)
      );
    },
  };

  // Midnight provider — submits finalized transactions to the network
  const midnightProvider = {
    submitTx: async (tx: any): Promise<string> => {
      await connectedAPI.submitTransaction(toHex(tx.serialize()));
      const txIdentifiers = tx.identifiers();
      console.log('[Midnight] Submitted transaction:', txIdentifiers);
      return txIdentifiers[0];
    },
  };

  return {
    privateStateProvider,
    publicDataProvider,
    zkConfigProvider,
    proofProvider,
    walletProvider,
    midnightProvider,
  };
}

/**
 * Find the deployed contract on Preprod and return a callable interface.
 */
export async function connectToDeployedContract(providers: MidnightProviders) {
  console.log('[Midnight] Finding deployed contract at:', PREPROD_CONTRACT_ADDRESS);

  const contract = new Contract({} as Witnesses<ZkCreatorPrivateState>);

  const foundContract = await findDeployedContract(providers, {
    contractAddress: PREPROD_CONTRACT_ADDRESS,
    compiledContract: contract as any,
  });

  console.log('[Midnight] Contract found! callTx interface available.');
  return foundContract;
}

/**
 * Read the current ledger state of the deployed contract.
 */
export function readLedgerState(contractState: any): Ledger {
  return ledger(contractState);
}
