import { Layers3, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ContentCard } from "@/components/ContentCard";
import { mockDrops } from "@/data/mockDrops";
import type { MidnightClient } from "@/hooks/useMidnight";

const categories = ["All Drops", "Airdrop Alpha", "Audits & Exploits", "Institutional DeFi"] as const;
export function ContentFeed({ midnight, unlockedIds, onUnlock }: { midnight: MidnightClient; unlockedIds: Record<string, string>; onUnlock: (id: string, nullifier: string) => void }) {
  const [category, setCategory] = useState<(typeof categories)[number]>("All Drops");
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => mockDrops.filter((item) => (category === "All Drops" || item.category === category) && `${item.title} ${item.creator}`.toLowerCase().includes(search.toLowerCase())), [category, search]);
  return <section id="alpha-feed" className="mx-auto max-w-[1440px] px-5 pb-24 pt-16 lg:px-10"><div className="mb-8 flex flex-col justify-between gap-5 border-b border-border pb-6 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.22em] text-mint"><Layers3 size={13} /> Classified index / updated live</div><h2 className="font-display text-4xl font-semibold tracking-tight text-foreground">Dispatch dossier.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Intelligence released by proof, not identity.</p></div><div className="relative w-full lg:w-72"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Search alpha drops" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="QUERY ARCHIVE..." className="rounded-none border-border bg-surface-1 pl-9 font-mono text-[10px]" /></div></div><Tabs value={category} onValueChange={(value) => setCategory(value as (typeof categories)[number])} className="mb-8"><TabsList className="h-auto flex-wrap justify-start gap-0 rounded-none border border-border bg-surface-1 p-0"><TabsTrigger value="All Drops" className="rounded-none border-r border-border font-mono text-[9px] uppercase tracking-wider data-[state=active]:bg-foreground data-[state=active]:text-background">All Dispatches</TabsTrigger><TabsTrigger value="Airdrop Alpha" className="rounded-none border-r border-border font-mono text-[9px] uppercase tracking-wider data-[state=active]:bg-foreground data-[state=active]:text-background">Airdrop Intel</TabsTrigger><TabsTrigger value="Audits & Exploits" className="rounded-none border-r border-border font-mono text-[9px] uppercase tracking-wider data-[state=active]:bg-foreground data-[state=active]:text-background">Audits</TabsTrigger><TabsTrigger value="Institutional DeFi" className="rounded-none font-mono text-[9px] uppercase tracking-wider data-[state=active]:bg-foreground data-[state=active]:text-background">Institutional</TabsTrigger></TabsList></Tabs><div className="grid gap-7 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <ContentCard key={item.id} item={item} midnight={midnight} unlocked={Boolean(unlockedIds[item.id])} onUnlock={onUnlock} />)}</div>{filtered.length === 0 && <div className="border border-dashed border-border p-10 text-center font-mono text-xs text-muted-foreground">NO MATCHING DISPATCHES</div>}</section>;
}