import { FileCode2, Plus, WandSparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export function CreatorStudioModal() {
  const [open, setOpen] = useState(false);
  const [created, setCreated] = useState(false);
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" size="sm" className="rounded-none font-mono text-[9px] uppercase tracking-wider"><Plus size={13} /> Publish dispatch</Button></DialogTrigger><DialogContent className="border-border bg-surface-1 text-foreground sm:max-w-xl"><DialogHeader><div className="mb-3 flex h-10 w-10 items-center justify-center border border-border bg-code text-mint"><FileCode2 size={18} /></div><DialogTitle className="font-display text-2xl">Creator studio</DialogTitle><DialogDescription>Package a private signal behind a Compact eligibility circuit.</DialogDescription></DialogHeader>{created ? <div className="space-y-4 py-4"><div className="border border-mint/25 bg-mint/5 p-5 text-center"><WandSparkles className="mx-auto mb-3 text-mint" size={24} /><p className="font-display text-lg text-foreground">Circuit parameters simulated</p><p className="mt-1 text-sm text-muted-foreground">Your dispatch is ready for Midnight Preprod.</p></div><Button className="w-full rounded-none" onClick={() => { setCreated(false); setOpen(false); }}>Done</Button></div> : <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setCreated(true); }}><div className="grid gap-4 sm:grid-cols-2"><label className="font-mono text-[9px] tracking-wider text-muted-foreground sm:col-span-2">DROP TITLE<Input required placeholder="e.g. Q4 Liquidity Signal Map" className="mt-1.5 rounded-none border-border bg-code" /></label><label className="font-mono text-[9px] tracking-wider text-muted-foreground">CATEGORY<select className="mt-1.5 flex h-9 w-full rounded-none border border-border bg-code px-3 text-sm text-foreground"><option>Airdrop Alpha</option><option>Audits & Exploits</option><option>Institutional DeFi</option></select></label><label className="font-mono text-[9px] tracking-wider text-muted-foreground">GATING REQUIREMENT<Input required placeholder="Min tNIGHT balance" className="mt-1.5 rounded-none border-border bg-code" /></label><label className="font-mono text-[9px] tracking-wider text-muted-foreground sm:col-span-2">TEASER TEXT<Textarea required placeholder="What will prove irresistible?" className="mt-1.5 min-h-20 rounded-none border-border bg-code" /></label><label className="font-mono text-[9px] tracking-wider text-muted-foreground sm:col-span-2">SECRET CONTENT<Textarea required placeholder="The private content revealed after proof..." className="mt-1.5 min-h-24 rounded-none border-border bg-code" /></label></div><DialogFooter><Button type="submit" className="w-full rounded-none sm:w-auto"><WandSparkles size={15} /> Simulate & publish</Button></DialogFooter></form>}</DialogContent></Dialog>;
}